from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BASE_DIR.parent
DATA_DIR = PROJECT_ROOT / "data" / "gestures"
DYNAMIC_DATA_DIR = PROJECT_ROOT / "data" / "dynamic"
DYNAMIC_MODEL_DIR = PROJECT_ROOT / "models"
MODELS_DIR = PROJECT_ROOT / "models"
CONFIG_DIR = PROJECT_ROOT / "config"
ACTIONS_PATH = CONFIG_DIR / "actions.json"

DEFAULT_GESTURES = [
    "open_palm",
    "fist",
    "thumbs_up",
    "thumbs_down",
    "pinch",
]

MIN_SAMPLES_PER_CLASS = 10
MODEL_VERSION = "v1.0"

MODEL_FILENAME = "gesture_model.joblib"
LABELS_FILENAME = "gesture_labels.json"
FEATURE_META_FILENAME = "feature_meta.json"
EVALUATION_FILENAME = "evaluation.json"
DATASET_FILENAME = "gesture_dataset.csv"

MODEL_PATH = MODELS_DIR / MODEL_FILENAME
LABELS_PATH = MODELS_DIR / LABELS_FILENAME
FEATURE_META_PATH = MODELS_DIR / FEATURE_META_FILENAME
EVALUATION_PATH = MODELS_DIR / EVALUATION_FILENAME
DATASET_PATH = DATA_DIR / DATASET_FILENAME

DYNAMIC_SEQUENCE_LENGTH = 20
DYNAMIC_CLASSES = ["swipe_left", "swipe_right"]
DYNAMIC_MODEL_PATH = DYNAMIC_MODEL_DIR / "dynamic_gesture_model.joblib"
DYNAMIC_LABELS_PATH = DYNAMIC_MODEL_DIR / "dynamic_gesture_labels.json"
DYNAMIC_META_PATH = DYNAMIC_MODEL_DIR / "dynamic_feature_meta.json"
DYNAMIC_EVALUATION_PATH = DYNAMIC_MODEL_DIR / "dynamic_evaluation.json"
DYNAMIC_CONFIDENCE_THRESHOLD = 0.80
DYNAMIC_CONFIRMATION_COUNT = 2
DYNAMIC_RECORDING_DURATION = 5.0
DYNAMIC_COLLECTION_DURATION_SECONDS = DYNAMIC_RECORDING_DURATION
DYNAMIC_COLLECTION_COUNT_OPTIONS = [3, 10, 20, 30, 40]
DYNAMIC_MIN_VALID_FRAMES = 4
DYNAMIC_COLLECTION_PAUSE_SECONDS = 0.35

SWIPE_LEFT_ZONE = 0.35
SWIPE_RIGHT_ZONE = 0.65
MIN_SWIPE_DURATION = 0.30
MAX_SWIPE_DURATION = 2.5
MIN_HORIZONTAL_DISPLACEMENT = 0.10
DIRECTION_CONSISTENCY_THRESHOLD = 0.55
SWIPE_SMOOTHING_WINDOW = 5
SWIPE_COOLDOWN_SECONDS = 1.0
HAND_MISSING_GRACE_PERIOD = 0.4
SWIPE_VERTICAL_LIMIT = 0.30
SWIPE_DISPLAY_DURATION_SECONDS = 1.5
